pool:
  vmImage: ubuntu-latest
  
jobs:

- job: sonar
  workspace:
    clean: all
  displayName:  Code Review
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'DevSecOps'
      organization: 'TareasUsach'
      projectKey: 'TareasUsach_spring-boot-kubernetes'
      projectName: 'spring-boot-kubernetes'
    displayName: 'Preparing Sonarqube Environment'

    
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Analysis Results'