# Angelo 
trigger:
- master

pool:
  vmImage: ubuntu-latest

- job: sonar
  workspace:
    clean: all
  displayName:  Code Review
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'DevSecOps'
      organization: 'TareasUsach'
      projectKey: 'tareasusach'
      projectName: 'TareasUsach_spring-boot-kubernetes'
    displayName: 'Preparing Sonarqube Environment'
