pool:
  vmImage: ubuntu-latest
  
jobs:

- job: sonar
  workspace:
    clean: all
  displayName:  Code Review
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'DevSecOps'
      organization: 'tareasusach'
      projectKey: 'TareasUsach_spring-boot-kubernetes'
      projectName: 'spring-boot-kubernetes'
    displayName: 'Preparing Sonarqube Environment'

- task: Gradle@3
  inputs:
     gradleWrapperFile: 'gradlew'
     task: "sonarqube"
     javaHomeOption: 'JDKVersion'
     sonarQubeRunAnalysis: true
     sqGradlePluginVersionChoice: 'specify'
     sonarQubeGradlePluginVersion: '3.3'
  displayName: 'Analyze current Branch'


    
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Analysis Results'